INSULIN_YAML = """sequences:
  - protein:
      id: [A]
      sequence: GIVEQCCTSICSLYQLENYCN
  - protein:
      id: [B]
      sequence: FVNQHLCGSHLVEALYLVCGERGFFYTPKT
"""

ANTIBODY_ANTIGEN_YAML = """sequences:
  - protein:
      id: [H]
      sequence: QVQLQQSGAELARPGASVKMSCKASGYTFTRYTMHWVKQRPGQGLEWIGYINPSRGYTNYNQKFKDKATLTTDKSSSTAYMQLSSLTSEDSAVYYCARYYDDHYCLDYWGQGTTLTVSS
  - protein:
      id: [L]
      sequence: DIQMTQSPSSLSASLGGKVTITCKASQDINSYLSWFQQKPGKSPKTLIYRANRLVDGVPSRFSGSGSGQDYSLTISSLESDDTATYYCLQYDEFPLTFGAGTKLELK
  - protein:
      id: [A]
      sequence: MKFLKFSLLTAVLLSVVFAFSSCGDDDDKQYKANNSKFVHLEIVSRIQEKRKQKQKVPPGPHCVPSPQCRGRKGRCCPDTCGIKCLDPVDTPNPTRSRPSMPPSSQPSLPQPAPQPTPIPSQPVPPQSQLPPQPQPPQSSQPHPQPLPQPSSALGGILLHAPRERARRGSSWQPPSEDIWKKFELLPTPPLSP
"""

